### ISSUE TITLE
Questions about dataset

### ISSUE THREAD

**Issue by hzw20200301** [DRSY/EasyKV#2]
Hi, sorry to bother.
Thanks for your great job! I have a question about the summarization experiment. I would like to know if you used **the entire test set** or only **extracted 1000 samples** from the xsum and CNN datasets for abstract text summarization tasks?
Thanks a lot!

**Comment by DRSY** [comment]
We only used the first 100 samples from the test set. Using more samples exhibits similar performance trend, so we just do it  this way for efficiency.

**Comment by hzw20200301** [comment]
Thank you for your prompt reply！！！
